[tool.poetry]
name = "tabletoppy"
version = "0.1.0"
description = "A Python library for simulating tabletop games, including dice rolls, coin tosses etc."
authors = ["peaky76 <robertjamespeacock@gmail.com>"]
license = "GPL-3.0-only"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
